prefix = "CategoricalInsVertivoreTree"
pairwise = "Carnivore-Herbivore"
GoSet = "KeggReactome"
GenePValueCutoff = 0.1
GoCategoryCutoff = 0.05
useStrictBoth = F

# ---- Read in files --- 
AssessGoCategoryDriver = function(prefix, pairwise, GoSet, GenePValueCutoff = 0.1, GoCategoryCutoff = 0.05, useStrictBoth = F){
  if(!is.null(pairwise)){
    directionailtyTableFileLoaction = paste0("Output/",prefix,"/", pairwise, "/", prefix, pairwise,"DriverTable.csv")
  }else{
    directionailtyTableFileLoaction = paste0("Output/",prefix,"/", prefix, "DriverTable.csv")
  }
  directionalityTable = read.csv(directionailtyTableFileLoaction)
  directionalityTable= directionalityTable[order(directionalityTable$main_p.adj),]
  
    
  if(!is.null(pairwise)){
    GoFileLoaction = paste0("Output/",prefix,"/", pairwise, "/", prefix, pairwise,"Enrichment-", GoSet, ".rds")
  }else{
    GoFileLoaction = paste0("Output/",prefix,"/", prefix, "Enrichment-", GoSet, ".rds")
  }
  GoData = readRDS(GoFileLoaction)
  GoData = GoData[[1]]
  GoData = GoData[which(GoData$p.adj < GoCategoryCutoff), ] #trim GoData to categories below cutoff
  
  # -- determine phenotype mappings --
  phenOneName = directionalityTable$Driver[which(directionalityTable$DriverNumeric == 1)[1]]
  phenTwoName = directionalityTable$Driver[which(directionalityTable$DriverNumeric == 2)[1]]
  
  significantGenes = directionalityTable[which(directionalityTable$main_p.adj < GenePValueCutoff),1]
  
  i = 1
  GoData$Driver = rep(NA, nrow(GoData))
  GoData$DriverNumeric = rep(NA, nrow(GoData))
  for(i in 1:nrow(GoData)){
    currentGeneset = GoData[i,]
    genesInSet = currentGeneset$gene.vals
    genesInSet = strsplit(genesInSet, ", ")
    genesInSet = genesInSet[[1]]
    genes = sub(":.*", "", genesInSet)
    positions = sub(".*:", "", genesInSet)
    names(genes) = positions
  
    relevantGenes = genes[genes %in% significantGenes]
    relevantDirectionality = directionalityTable[which(directionalityTable$X %in% relevantGenes),]
    
    numberofTotalGenes = nrow(relevantDirectionality)
    numberOfUnclearGenes = length(which(relevantDirectionality$DriverNumeric == 0))
    numberOfOneGenes = length(which(relevantDirectionality$DriverNumeric == 1))
    numberOfTwoGenes = length(which(relevantDirectionality$DriverNumeric == 2))
    numberOfBothGenes = length(which(relevantDirectionality$DriverNumeric %in% c(3,4)))
    numberOfStrictGenes = length(which(relevantDirectionality$DriverNumeric == 4))
    print(rownames(GoData)[i])
    directionalitySummary = data.frame(numberofTotalGenes, numberOfUnclearGenes, numberOfOneGenes, numberOfTwoGenes, numberOfBothGenes, numberOfStrictGenes)
    print(directionalitySummary)
    
    GoDirection = "Unclear"
    GoDirectionNumeric = 0 
    if(useStrictBoth){
      usedBothGenes = numberOfStrictGenes
    }else{
      usedBothGenes = numberOfBothGenes
    }
    
    if(usedBothGenes > 0.75*numberofTotalGenes){
      GoDirection = "Both"
      GoDirectionNumeric = 3
    }else if(numberOfOneGenes > 0.5*numberofTotalGenes | numberOfOneGenes+usedBothGenes > 0.75*numberofTotalGenes) {
      GoDirection = phenOneName
      GoDirectionNumeric = 1
    }else if(numberOfTwoGenes > 0.5*numberofTotalGenes| numberOfTwoGenes+usedBothGenes > 0.75*numberofTotalGenes) {
      GoDirection = phenTwoName
      GoDirectionNumeric = 2
    }else if(numberOfOneGenes+numberOfTwoGenes > 0.75*numberofTotalGenes) {
      GoDirection = "MixOfBoth"
      GoDirectionNumeric = 4
    }
    
    GoData$Driver[i] = GoDirection
    GoData$DriverNumeric[i] = GoDirectionNumeric
  }
  GoData
}

goCatgeories = c("KEGG_ABC_TRANSPORTERS","KEGG_ADHERENS_JUNCTION"
,"KEGG_ARGININE_AND_PROLINE_METABOLISM"
,"KEGG_BETA_ALANINE_METABOLISM"
,"KEGG_CALCIUM_SIGNALING_PATHWAY"
,"KEGG_COMPLEMENT_AND_COAGULATION_CASCADES"
,"KEGG_DRUG_METABOLISM_CYTOCHROME_P450"
,"KEGG_FATTY_ACID_METABOLISM"
,"KEGG_FOCAL_ADHESION"
,"KEGG_GAP_JUNCTION"
,"KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM"
,"KEGG_MAPK_SIGNALING_PATHWAY"
,"KEGG_METABOLISM_OF_XENOBIOTICS_BY_CYTOCHROME_P450"
,"KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION"
,"KEGG_NITROGEN_METABOLISM"
,"KEGG_OLFACTORY_TRANSDUCTION"
,"KEGG_OXIDATIVE_PHOSPHORYLATION"
,"KEGG_P53_SIGNALING_PATHWAY"
,"KEGG_PATHWAYS_IN_CANCER"
,"KEGG_PEROXISOME"
,"KEGG_PPAR_SIGNALING_PATHWAY"
,"KEGG_PROPANOATE_METABOLISM"
,"KEGG_PURINE_METABOLISM"
,"KEGG_REGULATION_OF_ACTIN_CYTOSKELETON"
,"KEGG_SMALL_CELL_LUNG_CANCER"
,"KEGG_SPLICEOSOME"
,"KEGG_STEROID_HORMONE_BIOSYNTHESIS"
,"KEGG_SULFUR_METABOLISM"
,"KEGG_TGF_BETA_SIGNALING_PATHWAY"
,"KEGG_TIGHT_JUNCTION"
,"KEGG_TRYPTOPHAN_METABOLISM"
,"KEGG_TYROSINE_METABOLISM"
,"KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION"
,"REACTOME_ABORTIVE_ELONGATION_OF_HIV_1_TRANSCRIPT_IN_THE_ABSENCE_OF_TAT"
,"REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3"
,"REACTOME_ACTIVATED_TAK1_MEDIATES_P38_MAPK_ACTIVATION"
,"REACTOME_ACTIVATION_OF_AMPK_DOWNSTREAM_OF_NMDARS"
,"REACTOME_ACTIVATION_OF_ANTERIOR_HOX_GENES_IN_HINDBRAIN_DEVELOPMENT_DURING_EARLY_EMBRYOGENESIS"
,"REACTOME_ACTIVATION_OF_KAINATE_RECEPTORS_UPON_GLUTAMATE_BINDING"
,"REACTOME_ACTIVATION_OF_NMDA_RECEPTORS_AND_POSTSYNAPTIC_EVENTS"
,"REACTOME_ACYL_CHAIN_REMODELLING_OF_PC"
,"REACTOME_AMINO_ACID_TRANSPORT_ACROSS_THE_PLASMA_MEMBRANE"
,"REACTOME_AMYLOID_FIBER_FORMATION"
,"REACTOME_ANTIGEN_PROCESSING_UBIQUITINATION_PROTEASOME_DEGRADATION"
,"REACTOME_APOPTOTIC_EXECUTION_PHASE"
,"REACTOME_ASSEMBLY_AND_CELL_SURFACE_PRESENTATION_OF_NMDA_RECEPTORS"
,"REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION"
,"REACTOME_ATTENUATION_PHASE"
,"REACTOME_BETA_CATENIN_INDEPENDENT_WNT_SIGNALING"
,"REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS"
,"REACTOME_BILE_ACID_AND_BILE_SALT_METABOLISM"
,"REACTOME_BIOLOGICAL_OXIDATIONS"
,"REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM"
,"REACTOME_BRANCHED_CHAIN_AMINO_ACID_CATABOLISM"
,"REACTOME_CA2_PATHWAY"
,"REACTOME_CARDIAC_CONDUCTION"
,"REACTOME_CARGO_RECOGNITION_FOR_CLATHRIN_MEDIATED_ENDOCYTOSIS"
,"REACTOME_CA_DEPENDENT_EVENTS"
,"REACTOME_CELLULAR_RESPONSES_TO_STIMULI"
,"REACTOME_CELLULAR_RESPONSE_TO_HEAT_STRESS"
,"REACTOME_CELLULAR_SENESCENCE"
,"REACTOME_CHOLINE_CATABOLISM"
,"REACTOME_CHROMATIN_MODIFYING_ENZYMES"
,"REACTOME_CLATHRIN_MEDIATED_ENDOCYTOSIS"
,"REACTOME_COBALAMIN_CBL_VITAMIN_B12_TRANSPORT_AND_METABOLISM"
,"REACTOME_COMPLEX_I_BIOGENESIS"
,"REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES"
,"REACTOME_COOPERATION_OF_PREFOLDIN_AND_TRIC_CCT_IN_ACTIN_AND_TUBULIN_FOLDING"
,"REACTOME_COPII_MEDIATED_VESICLE_TRANSPORT"
,"REACTOME_COPI_INDEPENDENT_GOLGI_TO_ER_RETROGRADE_TRAFFIC"
,"REACTOME_CREB1_PHOSPHORYLATION_THROUGH_NMDA_RECEPTOR_MEDIATED_ACTIVATION_OF_RAS_SIGNALING"
,"REACTOME_CYCLIN_D_ASSOCIATED_EVENTS_IN_G1"
,"REACTOME_CYTOCHROME_P450_ARRANGED_BY_SUBSTRATE_TYPE"
,"REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM"
,"REACTOME_CYTOSOLIC_SULFONATION_OF_SMALL_MOLECULES"
,"REACTOME_DAG_AND_IP3_SIGNALING"
,"REACTOME_DEFECTS_IN_VITAMIN_AND_COFACTOR_METABOLISM"
,"REACTOME_DEGRADATION_OF_THE_EXTRACELLULAR_MATRIX"
,"REACTOME_DEUBIQUITINATION"
,"REACTOME_DEVELOPMENTAL_BIOLOGY"
,"REACTOME_DIGESTION"
,"REACTOME_DIGESTION_AND_ABSORPTION"
,"REACTOME_DIGESTION_OF_DIETARY_LIPID"
,"REACTOME_DISEASES_OF_DNA_REPAIR"
,"REACTOME_DISEASES_OF_METABOLISM"
,"REACTOME_DISEASES_OF_PROGRAMMED_CELL_DEATH"
,"REACTOME_DISEASES_OF_SIGNAL_TRANSDUCTION_BY_GROWTH_FACTOR_RECEPTORS_AND_SECOND_MESSENGERS"
,"REACTOME_DNA_DAMAGE_TELOMERE_STRESS_INDUCED_SENESCENCE"
,"REACTOME_DNA_DOUBLE_STRAND_BREAK_REPAIR"
,"REACTOME_DNA_METHYLATION"
,"REACTOME_DNA_REPAIR"
,"REACTOME_DRUG_ADME"
,"REACTOME_DRUG_MEDIATED_INHIBITION_OF_CDK4_CDK6_ACTIVITY"
,"REACTOME_E3_UBIQUITIN_LIGASES_UBIQUITINATE_TARGET_PROTEINS"
,"REACTOME_EPH_EPHRIN_MEDIATED_REPULSION_OF_CELLS"
,"REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION"
,"REACTOME_ERKS_ARE_INACTIVATED"
,"REACTOME_ERK_MAPK_TARGETS"
,"REACTOME_ERYTHROCYTES_TAKE_UP_CARBON_DIOXIDE_AND_RELEASE_OXYGEN"
,"REACTOME_ERYTHROCYTES_TAKE_UP_OXYGEN_AND_RELEASE_CARBON_DIOXIDE"
,"REACTOME_ER_TO_GOLGI_ANTEROGRADE_TRANSPORT"
,"REACTOME_ESR_MEDIATED_SIGNALING"
,"REACTOME_ESTROGEN_DEPENDENT_GENE_EXPRESSION"
,"REACTOME_EXTRA_NUCLEAR_ESTROGEN_SIGNALING"
,"REACTOME_FANCONI_ANEMIA_PATHWAY"
,"REACTOME_FATTY_ACID_METABOLISM"
,"REACTOME_FERTILIZATION"
,"REACTOME_FGFR2_ALTERNATIVE_SPLICING"
,"REACTOME_FGFR2_MUTANT_RECEPTOR_ACTIVATION"
,"REACTOME_FLT3_SIGNALING_BY_CBL_MUTANTS"
,"REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE"
,"REACTOME_FORMATION_OF_RNA_POL_II_ELONGATION_COMPLEX"
,"REACTOME_FORMATION_OF_SENESCENCE_ASSOCIATED_HETEROCHROMATIN_FOCI_SAHF"
,"REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE"
,"REACTOME_FORMATION_OF_THE_EARLY_ELONGATION_COMPLEX"
,"REACTOME_GABA_B_RECEPTOR_ACTIVATION"
,"REACTOME_GABA_RECEPTOR_ACTIVATION"
,"REACTOME_GENE_SILENCING_BY_RNA"
,"REACTOME_GLUCAGON_LIKE_PEPTIDE_1_GLP1_REGULATES_INSULIN_SECRETION"
,"REACTOME_GLYCOGEN_METABOLISM"
,"REACTOME_GLYCOLYSIS"
,"REACTOME_GLYOXYLATE_METABOLISM_AND_GLYCINE_DEGRADATION"
,"REACTOME_GPER1_SIGNALING"
,"REACTOME_G_ALPHA_I_SIGNALLING_EVENTS"
,"REACTOME_G_ALPHA_S_SIGNALLING_EVENTS"
,"REACTOME_G_ALPHA_Z_SIGNALLING_EVENTS"
,"REACTOME_G_PROTEIN_MEDIATED_EVENTS"
,"REACTOME_HATS_ACETYLATE_HISTONES"
,"REACTOME_HCMV_EARLY_EVENTS"
,"REACTOME_HCMV_INFECTION"
,"REACTOME_HCMV_LATE_EVENTS"
,"REACTOME_HDACS_DEACETYLATE_HISTONES"
,"REACTOME_HDR_THROUGH_HOMOLOGOUS_RECOMBINATION_HRR"
,"REACTOME_HDR_THROUGH_SINGLE_STRAND_ANNEALING_SSA"
,"REACTOME_HIV_INFECTION"
,"REACTOME_HIV_LIFE_CYCLE"
,"REACTOME_HIV_TRANSCRIPTION_ELONGATION"
,"REACTOME_HOMOLOGOUS_DNA_PAIRING_AND_STRAND_EXCHANGE"
,"REACTOME_HOMOLOGY_DIRECTED_REPAIR"
,"REACTOME_HOST_INTERACTIONS_OF_HIV_FACTORS"
,"REACTOME_HSF1_DEPENDENT_TRANSACTIVATION"
,"REACTOME_INFECTIOUS_DISEASE"
,"REACTOME_INFLUENZA_INFECTION"
,"REACTOME_INTEGRATION_OF_ENERGY_METABOLISM"
,"REACTOME_INTERLEUKIN_17_SIGNALING"
,"REACTOME_INTRACELLULAR_SIGNALING_BY_SECOND_MESSENGERS"
,"REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION"
,"REACTOME_INWARDLY_RECTIFYING_K_CHANNELS"
,"REACTOME_IONOTROPIC_ACTIVITY_OF_KAINATE_RECEPTORS"
,"REACTOME_ION_HOMEOSTASIS"
,"REACTOME_KERATINIZATION"
,"REACTOME_L1CAM_INTERACTIONS"
,"REACTOME_LONG_TERM_POTENTIATION"
,"REACTOME_MAPK6_MAPK4_SIGNALING"
,"REACTOME_MAPK_FAMILY_SIGNALING_CASCADES"
,"REACTOME_MAPK_TARGETS_NUCLEAR_EVENTS_MEDIATED_BY_MAP_KINASES"
,"REACTOME_MEIOTIC_SYNAPSIS"
,"REACTOME_MEMBRANE_TRAFFICKING"
,"REACTOME_METABOLIC_DISORDERS_OF_BIOLOGICAL_OXIDATION_ENZYMES"
,"REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES"
,"REACTOME_METABOLISM_OF_LIPIDS"
,"REACTOME_METABOLISM_OF_RNA"
,"REACTOME_METABOLISM_OF_STEROIDS"
,"REACTOME_METABOLISM_OF_VITAMINS_AND_COFACTORS"
,"REACTOME_METABOLISM_OF_WATER_SOLUBLE_VITAMINS_AND_COFACTORS"
,"REACTOME_MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION"
,"REACTOME_MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION_OF_SATURATED_FATTY_ACIDS"
,"REACTOME_MITOCHONDRIAL_TRANSLATION"
,"REACTOME_MITOCHONDRIAL_TRNA_AMINOACYLATION"
,"REACTOME_MITOTIC_PROPHASE"
,"REACTOME_MRNA_SPLICING"
,"REACTOME_MRNA_SPLICING_MINOR_PATHWAY"
,"REACTOME_MUCOPOLYSACCHARIDOSES"
,"REACTOME_MULTIFUNCTIONAL_ANION_EXCHANGERS"
,"REACTOME_MUSCARINIC_ACETYLCHOLINE_RECEPTORS"
,"REACTOME_MUSCLE_CONTRACTION"
,"REACTOME_MYD88_INDEPENDENT_TLR4_CASCADE"
,"REACTOME_NEDDYLATION"
,"REACTOME_NEGATIVE_EPIGENETIC_REGULATION_OF_RRNA_EXPRESSION"
,"REACTOME_NEGATIVE_REGULATION_OF_MAPK_PATHWAY"
,"REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION"
,"REACTOME_NERVOUS_SYSTEM_DEVELOPMENT"
,"REACTOME_NEUREXINS_AND_NEUROLIGINS"
,"REACTOME_NEURONAL_SYSTEM"
,"REACTOME_NEUROTOXICITY_OF_CLOSTRIDIUM_TOXINS"
,"REACTOME_NEUROTRANSMITTER_RECEPTORS_AND_POSTSYNAPTIC_SIGNAL_TRANSMISSION"
,"REACTOME_NON_INTEGRIN_MEMBRANE_ECM_INTERACTIONS"
,"REACTOME_NUCLEAR_ENVELOPE_BREAKDOWN"
,"REACTOME_NUCLEAR_ENVELOPE_NE_REASSEMBLY"
,"REACTOME_NUCLEAR_EVENTS_KINASE_AND_TRANSCRIPTION_FACTOR_ACTIVATION"
,"REACTOME_OLFACTORY_SIGNALING_PATHWAY"
,"REACTOME_ONCOGENE_INDUCED_SENESCENCE"
,"REACTOME_OPIOID_SIGNALLING"
,"REACTOME_OVARIAN_TUMOR_DOMAIN_PROTEASES"
,"REACTOME_OXIDATIVE_STRESS_INDUCED_SENESCENCE"
,"REACTOME_PEROXISOMAL_LIPID_METABOLISM"
,"REACTOME_PEROXISOMAL_PROTEIN_IMPORT"
,"REACTOME_PHASE_0_RAPID_DEPOLARISATION"
,"REACTOME_PHASE_II_CONJUGATION_OF_COMPOUNDS"
,"REACTOME_PHASE_I_FUNCTIONALIZATION_OF_COMPOUNDS"
,"REACTOME_PIWI_INTERACTING_RNA_PIRNA_BIOGENESIS"
,"REACTOME_PLATELET_HOMEOSTASIS"
,"REACTOME_POSITIVE_EPIGENETIC_REGULATION_OF_RRNA_EXPRESSION"
,"REACTOME_POST_TRANSLATIONAL_PROTEIN_MODIFICATION"
,"REACTOME_POTASSIUM_CHANNELS"
,"REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA"
,"REACTOME_PREVENTION_OF_PHAGOSOMAL_LYSOSOMAL_FUSION"
,"REACTOME_PRE_NOTCH_EXPRESSION_AND_PROCESSING"
,"REACTOME_PROCESSING_OF_CAPPED_INTRONLESS_PRE_MRNA"
,"REACTOME_PROCESSING_OF_CAPPED_INTRON_CONTAINING_PRE_MRNA"
,"REACTOME_PROCESSING_OF_INTRONLESS_PRE_MRNAS"
,"REACTOME_PROSTACYCLIN_SIGNALLING_THROUGH_PROSTACYCLIN_RECEPTOR"
,"REACTOME_PROTEIN_FOLDING"
,"REACTOME_PROTEIN_LOCALIZATION"
,"REACTOME_PROTEIN_PROTEIN_INTERACTIONS_AT_SYNAPSES"
,"REACTOME_PROTEIN_UBIQUITINATION"
,"REACTOME_PTEN_REGULATION"
,"REACTOME_PYRIMIDINE_SALVAGE"
,"REACTOME_RAC2_GTPASE_CYCLE"
,"REACTOME_RAS_ACTIVATION_UPON_CA2_INFLUX_THROUGH_NMDA_RECEPTOR"
,"REACTOME_RECEPTOR_TYPE_TYROSINE_PROTEIN_PHOSPHATASES"
,"REACTOME_RECYCLING_OF_BILE_ACIDS_AND_SALTS"
,"REACTOME_RECYCLING_PATHWAY_OF_L1"
,"REACTOME_REGULATION_OF_HSF1_MEDIATED_HEAT_SHOCK_RESPONSE"
,"REACTOME_REGULATION_OF_INSULIN_SECRETION"
,"REACTOME_REGULATION_OF_RUNX1_EXPRESSION_AND_ACTIVITY"
,"REACTOME_RESOLUTION_OF_D_LOOP_STRUCTURES"
,"REACTOME_RESOLUTION_OF_D_LOOP_STRUCTURES_THROUGH_SYNTHESIS_DEPENDENT_STRAND_ANNEALING_SDSA"
,"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT"
,"REACTOME_RESPIRATORY_ELECTRON_TRANSPORT_A,TP_SYNTHESIS_BY_CHEMIOSMOTIC_COUPLING_AND_HEAT_PRODUCTION_BY_UNCOUPLING_PROTEINS"
,"REACTOME_RESPONSE_OF_MTB_TO_PHAGOCYTOSIS"
,"REACTOME_RETROGRADE_NEUROTROPHIN_SIGNALLING"
,"REACTOME_RHOG_GTPASE_CYCLE"
,"REACTOME_RHO_GTPASES_ACTIVATE_PKNS"
,"REACTOME_RIPK1_MEDIATED_REGULATED_NECROSIS"
,"REACTOME_RMTS_METHYLATE_HISTONE_ARGININES"
,"REACTOME_RNA_POLYMERASE_II_PRE_TRANSCRIPTION_EVENTS"
,"REACTOME_RNA_POLYMERASE_II_TRANSCRIPTION"
,"REACTOME_RNA_POLYMERASE_II_TRANSCRIPTION_TERMINATION"
,"REACTOME_RNA_POLYMERASE_I_PROMOTER_ESCAPE"
,"REACTOME_RNA_POLYMERASE_I_TRANSCRIPTION"
,"REACTOME_RUNX1_REGULATES_GENES_INVOLVED_IN_MEGAKARYOCYTE_DIFFERENTIATION_AND_PLATELET_FUNCTION"
,"REACTOME_RUNX1_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_DIFFERENTIATION_OF_HSCS"
,"REACTOME_SENESCENCE_ASSOCIATED_SECRETORY_PHENOTYPE_SASP"
,"REACTOME_SIGNALING_BY_FGFR"
,"REACTOME_SIGNALING_BY_FGFR2"
,"REACTOME_SIGNALING_BY_GPCR"
,"REACTOME_SIGNALING_BY_INTERLEUKINS"
,"REACTOME_SIGNALING_BY_NOTCH"
,"REACTOME_SIGNALING_BY_NTRKS"
,"REACTOME_SIGNALING_BY_NUCLEAR_RECEPTORS"
,"REACTOME_SIGNALING_BY_RECEPTOR_TYROSINE_KINASES"
,"REACTOME_SIGNALING_BY_TGFB_FAMILY_MEMBERS"
,"REACTOME_SIGNALING_BY_TGF_BETA_RECEPTOR_COMPLEX"
,"REACTOME_SIGNALING_BY_WNT"
,"REACTOME_SIGNAL_AMPLIFICATION"
,"REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION"
,"REACTOME_SLBP_DEPENDENT_PROCESSING_OF_REPLICATION_DEPENDENT_HISTONE_PRE_MRNAS"
,"REACTOME_SLC_MEDIATED_TRANSMEMBRANE_TRANSPORT"
,"REACTOME_SPERM_MOTILITY_AND_TAXES"
,"REACTOME_STRIATED_MUSCLE_CONTRACTION"
,"REACTOME_SULFUR_AMINO_ACID_METABOLISM"
,"REACTOME_SUMOYLATION_OF_CHROMATIN_ORGANIZATION_PROTEINS"
,"REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL"
,"REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_7ALPHA_HYDROXYCHOLESTEROL"
,"REACTOME_TGF_BETA_RECEPTOR_SIGNALING_ACTIVATES_SMADS"
,"REACTOME_THROMBOXANE_SIGNALLING_THROUGH_TP_RECEPTOR"
,"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_RUNX1"
,"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS"
,"REACTOME_TRANSCRIPTIONAL_REGULATION_BY_TP53"
,"REACTOME_TRANSCRIPTIONAL_REGULATION_OF_GRANULOPOIESIS"
,"REACTOME_TRANSCRIPTION_OF_THE_HIV_GENOME"
,"REACTOME_TRANSLATION"
,"REACTOME_TRANSMISSION_ACROSS_CHEMICAL_SYNAPSES"
,"REACTOME_TRANSPORT_OF_BILE_SALTS_AND_ORGANIC_ACIDS_METAL_IONS_AND_AMINE_COMPOUNDS"
,"REACTOME_TRANSPORT_OF_MATURE_MRNAS_DERIVED_FROM_INTRONLESS_TRANSCRIPTS"
,"REACTOME_TRANSPORT_OF_MATURE_TRANSCRIPT_TO_CYTOPLASM"
,"REACTOME_TRANSPORT_OF_THE_SLBP_DEPENDANT_MATURE_MRNA"
,"REACTOME_TRP_CHANNELS"
,"REACTOME_TRYPTOPHAN_CATABOLISM"
,"REACTOME_TYROSINE_CATABOLISM"
,"REACTOME_UB_SPECIFIC_PROCESSING_PROTEASES"
,"REACTOME_UNBLOCKING_OF_NMDA_RECEPTORS_GLUTAMATE_BINDING_AND_ACTIVATION"
,"REACTOME_UPTAKE_OF_DIETARY_COBALAMINS_INTO_ENTEROCYTES"
,"REACTOME_UREA_CYCLE"
,"REACTOME_VASOPRESSIN_REGULATES_RENAL_WATER_HOMEOSTASIS_VIA_AQUAPORINS"
,"REACTOME_VESICLE_MEDIATED_TRANSPORT"
,"REACTOME_VIRAL_MESSENGER_RNA_SYNTHESIS"
,"REACTOME_VITAMINS"
,"REACTOME_VITAMIN_D_CALCIFEROL_METABOLISM"
,"REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS")
#currentOutput = GODirecitonality[(rownames(GODirecitonality) %in% goCatgeories),]

#currentOutput = currentOutput[order(rownames(currentOutput)),]
#View(currentOutput)

#write.csv(currentOutput, "Results/temp.csv")
